### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by innovatemaker** [dumptyd/omegle-node#1]
```
//emitted when you get a message
om.on('gotMessage',function(msg){
    console.log('Ответ: ' + msg);

    if (msg=='hi' || msg=='hey' || msg=='hello' || msg=='Hi' || msg=='Hey' || msg=='Hello') {
    om.send('Hi'); //used to send a message to the stranger
    console.log('Здороваемся в ответ');
    }
    else if (msg.search('M') != -1  || msg.search('m') != -1){
    console.log('Отправляем приглашение в скайп');
    om.send('Bye Bye);
    om.send('bye Bye');
    om.disconnect();
        om.connect();
    }
    else {
    om.send('So m or f?');
    console.log('Переспрашиваем пол');
    }
```

![2016-08-27 13 32 43](https://cloud.githubusercontent.com/assets/20598279/18026821/d8f06a2c-6c5a-11e6-9798-12c689df9f1b.png)

```
/root/node_modules/omegle-node/index.js:171
                                        for(j = 1; j<ev[i].length; ++j)
                                                          ^

TypeError: Cannot read property 'length' of undefined
    at emitEvents (/root/node_modules/omegle-node/index.js:171:24)
    at /root/node_modules/omegle-node/index.js:111:6
    at Request._callback (/root/node_modules/omegle-node/index.js:60:12)
    at Request.self.callback (/root/node_modules/omegle-node/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/node_modules/omegle-node/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/node_modules/omegle-node/node_modules/request/request.js:965:12)
```

**Comment by dumptyd** [comment]
My bad, I forgot to add the documentation for `disconnected` event. You're only supposed to call `connect()` again after there's a `disconnected` or `strangerDisconnected` event. 

I'll update the documentation soon. 

This should work for you: 

``` javascript
om.on('gotMessage',function(msg){
    console.log('Ответ: ' + msg);

    if (msg=='hi' || msg=='hey' || msg=='hello' || msg=='Hi' || msg=='Hey' || msg=='Hello') {
        om.send('Hi'); //used to send a message to the stranger
        console.log('Здороваемся в ответ');
    }
    else if (msg.search('M') != -1  || msg.search('m') != -1){
        console.log('Отправляем приглашение в скайп');
        om.send('Bye Bye');
        om.send('bye Bye');
        om.disconnect();
    }
    else {
        om.send('So m or f?');
        console.log('Переспрашиваем пол');}
    });
om.on('disconnected',function(){
    om.connect();
});
```

Also, don't send messages instantly after you receive one from the stranger and do send your typing status regularly, if you don't want to get banned from Omegle.

**Comment by innovatemaker** [comment]
I use
    `setTimeout(function() { om.disconnect() }, 30000);`

**Comment by dumptyd** [comment]
Added documentation for `disconnected` event.
